### ISSUE TITLE
Would this interest you?

### ISSUE THREAD

**Issue by StuartIanNaylor** [bastibe/simple-cython-limiter#2]
Hopefully.

Basically its all in https://invensense.tdk.com/wp-content/uploads/2015/02/Microphone-Array-Beamforming.pdf

The EQ could probably be done with AlsaEQ and also again using asound.conf we could resample.

So with a stereo pair of mics say https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-test ?
The above runs with an example at 48Khz 2 Mics 21mm with a 3-sample-delay (7mm speed of sound).

So all we have to do is rotate 3 samples of delay and the 3rd is inverted and stored at the current rear sample.
Alsa you can do a route sum so we can mix down to mono and resample to 16Khz with a asound.conf that also chains AlsaEQ to flatten out the high pass effect of the beamformer.

My Python is woeful and my C non existent and not that sure on a Pi but thinking its likely better to be C.
It would be great to get a simple directional mems mic on the Pi its isn't cutting edge beamforming but it will give a degree of directional noise suppression and far field directionality.

Fingers crossed as from Pi Cameras to VoiceAI it could be quite beneficial.

Stuart :)

Apols about my coding ability.

**Comment by bastibe** [comment]
Hey, thanks for reaching out. This looks like a fun project!

We did something similar with a 16-mic array on a Raspberry Pi at the university. Performance seems to work OK for these kinds of applications, and MEMS mics seem quite adequate for the job. There are commercial variants as well, such as the ReSpeaker.

Best of luck to you!

**Comment by StuartIanNaylor** [comment]
Yeah can not really do it with Respeaker as the mics are hardware placed.

The above just creates a simple endfire array of 2 mics inline to make directional.
There is only the higher value USB mics that have beamforming dsp the rest are simple arrays that we can not change the spacing to the speed of sound at 48khz or whatever sampling rate you choose.
48khz still only gives just over 7mm per sample and in the invensense app they use 21mm and a 3 sample delay.

Are you sure I can not twist your arm? :)
