### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [bastibe/simple-cython-limiter#3]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://forart.it/HyMPS/) (under the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Effects section](https://github.com/forart/HyMPS/blob/main/Audio/Effects.md#--) \ [General page](https://github.com/forart/HyMPS/blob/main/Audio/GeneralFX.md#---) \ [Limiting subsection](https://github.com/forart/HyMPS/blob/main/Audio/GeneralFX.md#limiting-)), can you please add the license to it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/bastibe/simple-cython-limiter/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/bastibe/simple-cython-limiter/?label=LICENSE)

Anyway you can easily set a standard one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by bastibe** [comment]
Sure thing. The blog post is licensed CC-BY-SA, as stated on the linked blog post. I've added a GPL V3 license to the code repository.

**Comment by MarcoRavich** [comment]
As you can see, the badge works now.

Thanks !
